FROM node:20-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends default-jre-headless curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN npm install -g firebase-tools

COPY firebase.json .
COPY firestore.rules .
COPY firestore.indexes.json .
COPY storage.rules .
COPY .firebaserc .

EXPOSE 9099 8080 9199 4000

CMD ["firebase", "emulators:start", "--only", "auth,firestore,storage", "--project", "ham-sandwich"]
